spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: true


#logging:
#  level:
#    org.hibernate.SQL: debug

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: false

# 시큐리티
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

config:
  domain: "*"