spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      #format_sql: true #sql 쿼리 로그 보기
      ddl-auto: create
      #create: 기존테이블 삭제 후 다시 생성 (DROP + CREATE) <- test 환경에서 사용하면 좋음
      #create-drop: create와 같으나 종료시점에 테이블 DROP <- test 환경에서 사용하면 좋음
      #update: 변경분만 반영(운영DB에서는 사용하면 안됨) <- test 환경에서 사용하면 좋음
      #validate: 엔티티와 테이블이 정상 매핑되었는지만 확인 <- 운영단계에서 사용하면 좋음
      #none: 사용하지 않음 <- 운영단계에서 사용하면 좋음
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


#logging:
#  level:
#    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: false
